name = "ImageComponentAnalysis"
uuid = "d9b9e9a0-1569-11e9-2cb5-bbca914b0e89"
authors = ["Dr. Zygmunt L. Szpak <zygmunt.szpak@gmail.com>"]
version = "0.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LeftChildRightSiblingTrees = "1d6d02ad-be62-4b6b-8a6d-2f90e265016e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlanarConvexHulls = "145d500b-351c-58b3-a0aa-f5d7e249d989"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AbstractTrees = "0.3"
DataFrames = "0.19.4, 0.20"
DataStructures = "0.17.3, 0.17"
ImageFiltering = "0.6.5, 0.6"
LeftChildRightSiblingTrees = "0.1"
OffsetArrays = "0.11.3, 1"
Parameters = "0.12.0"
PlanarConvexHulls = "0.3.0"
StaticArrays = "0.11.1, 0.12"
julia = "1.1.0, 1"

[extras]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AbstractTrees", "ImageCore", "DataFrames", "Test", "StaticArrays"]
